#### 1. Pandas Library

In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\sreeman\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\sreeman\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sreeman\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sreeman\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sreeman\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\sreeman\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import numpy as np
import pandas as pd

#### 2. Create a Dataframe

In [2]:
# pd.DataFrame (data : ndarray, index : list, columns : list , copy)
# copy = True (new memory allocated, Forces Pandas to not reuse underlying NumPy memory), 
#        False (shares memory with original)
df = pd.DataFrame(data= np.arange(0,20).reshape(5,4), 
                    index=['Row1', 'Row2','Row3', 'Row4','Row5'],
                    columns= ['Column1','Column2','Column3','Column4']
                   )

#### 3. Get Details on Data Frame

In [7]:
# get the first five rows
df.head()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [8]:
# save in a csv file (coma seperated values)
df.to_csv('Pandas_Test_1.csv')

#### 3. Accessing Elements

##### A. Direct

In [31]:
df['Column3']

Row1     2
Row2     6
Row3    10
Row4    14
Row5    18
Name: Column3, dtype: int32

In [32]:
type(df['Column3'])

pandas.core.series.Series

In [34]:
# df[list of column names]
df[['Column1','Column2']]

      Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

##### B. df.loc [row, col] : data location (focus on row indexes mainly)

In [9]:
## Series o/p
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32

In [11]:
## Series o/p
df.loc[:,'Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [4]:
df.loc[df['Column1']<10, ['Column2','Column1']]

      Column2  Column1
Row1        1        0
Row2        5        4
Row3        9        8

##### C. df.iloc [row, col]  : (mainly focuses on columns and rows)

In [13]:
# : all rows / columns
df.iloc[:,:]

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [17]:
# dataframe
df.iloc[0:2,0:2]

      Column1  Column2
Row1        0        1
Row2        4        5

In [18]:
# series
df.iloc[0:2,0]

Row1    0
Row2    4
Name: Column1, dtype: int32

In [20]:
# remove the elements of column1
df.iloc[:,1:]

      Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

#### 4. Operations on Dataframe

##### A. Converting Dataframe into Arrays : .values

In [21]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [22]:
df.iloc[:,1:].values.shape

(5, 3)

##### B. Check null condition

In [24]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

##### C. Unique values and its count in a column / feature

In [27]:
df['Column1'].value_counts()

Column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [29]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])

#### 5. Reading Dataset